const state={access:sessionStorage.getItem('access'),refresh:sessionStorage.getItem('refresh'),overview:null,me:null,timer:null};
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const auth=()=>state.access?{Authorization:`Bearer ${state.access}`}:{}, fmt=n=>new Intl.NumberFormat('ko-KR').format(Number(n||0));
const ago=value=>{if(!value)return '—';const sec=Math.max(0,(Date.now()-new Date(value))/1000);if(sec<60)return `${Math.floor(sec)}초 전`;if(sec<3600)return `${Math.floor(sec/60)}분 전`;return new Date(value).toLocaleString('ko-KR')};
async function api(path,options={},retried=false){let r=await fetch(path,{...options,headers:{...auth(),...(options.headers||{})}});if(r.status===401&&path!=='/v1/auth/login'&&path!=='/v1/auth/refresh'){if(state.refresh&&!retried){const renewed=await fetch('/v1/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.refresh})});if(renewed.ok){const tokens=await renewed.json();saveTokens(tokens);return api(path,options,true)}}logout();throw new Error('로그인 세션이 만료되었습니다. 다시 로그인해 주세요.')}if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.detail||`요청 실패 (${r.status})`)}return r.json()}
function saveTokens(d){state.access=d.access_token;state.refresh=d.refresh_token||state.refresh;sessionStorage.setItem('access',state.access);if(state.refresh)sessionStorage.setItem('refresh',state.refresh)}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{const d=await api('/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});saveTokens(d);await start()}catch(err){$('loginError').textContent=err.message}});
async function start(){try{state.me=await api('/v1/me');$('identityName').textContent=state.me.display_name;$('identityRole').textContent=state.me.role.toUpperCase();$('identityAvatar').textContent=state.me.display_name.slice(0,1);$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await refresh();state.timer=setInterval(refresh,5000)}catch(err){$('loginError').textContent=err.message}}
function logout(){clearInterval(state.timer);sessionStorage.removeItem('access');sessionStorage.removeItem('refresh');state.access=null;state.refresh=null;$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}$('logout').onclick=logout;$('refresh').onclick=refresh;
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
function showView(id){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===id));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active-view',x.id===id));$('pageTitle').textContent={dashboard:'운영 대시보드',documents:'문서 저장소',search:'AI 검색',members:'사용자·그룹',logs:'통합 로그'}[id]}
async function refresh(){try{state.overview=await api('/v1/admin/dashboard/overview');render(state.overview)}catch(err){$('globalHealth').className='health bad';$('globalHealth').querySelector('span').textContent=err.message}}
function render(d){const good=d.status==='healthy';$('globalHealth').className=`health ${good?'good':'bad'}`;$('globalHealth').querySelector('span').textContent=good?'모든 시스템 정상':'확인 필요';$('updatedAt').textContent=`마지막 갱신 ${new Date(d.generated_at).toLocaleTimeString('ko-KR')}`;renderServices(d);renderKpis(d.opensql);renderNodes(d.nodes);renderWorkers(d.workers);renderQueues(d.rabbitmq);renderJobs(d.opensql,d.prometheus);renderDocuments(d.opensql.recent_documents||[]);renderGraph(d.opensql.memberships||{nodes:[],edges:[]});renderLogs(d.logs.items||[])}
function renderServices(d){const entries=[['OpenSQL',d.opensql],['RabbitMQ',d.rabbitmq],['Redis',d.workers],['Prometheus',d.prometheus],['Loki',d.logs],['Patroni',d.nodes]];$('serviceStrip').innerHTML=entries.map(([name,x])=>`<div class="service ${x.status}"><span>${name}</span><b>${x.status==='healthy'?'정상':x.status==='not_configured'?'미설정':'확인 필요'}</b></div>`).join('')}
function renderKpis(db){const items=[['문서',db.documents,'OpenSQL'],['청크',db.chunks,'검색 단위'],['임베딩',db.embeddings,'pgvector'],['사용자',db.users,'워크스페이스'],['엔티티',db.entities,'지식 그래프'],['Outbox 대기',db.outbox_pending,'미발행 이벤트']];$('kpis').innerHTML=items.map(([l,v,s])=>`<div class="kpi"><span>${l}</span><b>${fmt(v)}</b><small>${s}</small></div>`).join('')}
function renderNodes(nodes){const items=nodes.items||[];const primary=items.find(x=>x.role==='leader'||x.role==='primary');$('primaryBadge').textContent=`PRIMARY ${primary?.name||'—'}`;$('nodes').innerHTML=items.length?items.map(n=>`<div class="node"><i class="dot ${n.status==='healthy'?'':'bad'}"></i><div><b>${esc(n.name)}</b><span>${esc(n.state)}</span></div><span class="role">${esc(n.role).toUpperCase()}</span><span>Lag ${fmt(n.lag)} B</span></div>`).join(''):'<span class="empty">PATRONI_API_URLS를 설정하면 노드 역할과 복제 상태가 표시됩니다.</span>'}
function renderWorkers(workers){const items=workers.items||[];$('workerCount').textContent=`${items.length} ONLINE`;$('workers').innerHTML=items.length?items.map(w=>`<div class="worker"><i class="dot"></i><div><b>${esc(w.worker_id)}</b><span>${w.current_job_id?'작업 '+esc(w.current_job_id).slice(0,10):'대기 중'} · ${ago(w.last_heartbeat)}</span></div><span class="role">${esc(w.status).toUpperCase()}</span><span>${fmt(w.processed_total)}건</span></div>`).join(''):'<span class="empty">Redis heartbeat를 기다리고 있습니다. Worker를 시작해 주세요.</span>'}
function renderQueues(r){const qs=r.queues||[],max=Math.max(1,...qs.map(q=>q.ready+q.processing));$('queueTotals').textContent=`Ready ${fmt(r.ready)} · Retry ${fmt(r.retry)} · DLQ ${fmt(r.dlq)}`;$('queues').innerHTML=qs.length?qs.map(q=>`<div class="queue ${q.name.endsWith('.dlq')?'dlq':''}"><b>${esc(q.name.replace('tibero-doc.',''))}</b><div class="queue-track"><i style="width:${Math.max(2,(q.ready+q.processing)/max*100)}%"></i></div><span>${q.ready} 대기</span><span>${q.consumers} 소비자</span></div>`).join(''):'<span class="empty">RabbitMQ Management API 연결 정보가 필요합니다.</span>'}
function renderJobs(db,prom){const p=db.pipeline||{},vals=[p.completed||0,p.running||0,p.queued||0,p.failed||0],total=vals.reduce((a,b)=>a+b,0),colors=['#16a36a','#2358e8','#f59e0b','#e5484d'];let at=0;const stops=vals.map((v,i)=>{const from=at;at+=total?v/total*100:0;return `${colors[i]} ${from}% ${at}%`}).join(',');$('jobDonut').style.background=total?`conic-gradient(${stops})`:'#edf0f6';$('jobDonut').innerHTML=`<div><b>${fmt(total)}</b><span>TOTAL JOBS</span></div>`;$('jobLegend').innerHTML=['완료','실행 중','대기','실패'].map((x,i)=>`<div><span><i style="background:${colors[i]}"></i>${x}</span><b>${fmt(vals[i])}</b></div>`).join('');$('metrics').innerHTML=[['RPS',prom.requests_per_second],['p95',`${Number(prom.p95_seconds||0).toFixed(2)}s`],['Worker/s',prom.worker_jobs_per_second]].map(x=>`<div><b>${x[1]||0}</b><span>${x[0]}</span></div>`).join('')}
function renderDocuments(docs){$('recentDocuments').innerHTML=docs.length?docs.map(d=>`<tr><td><b>${esc(d.filename)}</b></td><td>${esc(d.owner||'—')}</td><td>v${d.version}</td><td>${fmt(d.chunk_count)}</td><td><span class="status-pill ${d.embedded?'':'pending'}">${d.embedded?'완료':'대기'}</span></td><td>${ago(d.updated_at)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">등록된 문서가 없습니다.</td></tr>';$('documentCards').innerHTML=docs.map(d=>`<article class="doc-card"><div class="doc-icon">${esc(d.filename.split('.').pop().toUpperCase().slice(0,3))}</div><h3 title="${esc(d.filename)}">${esc(d.filename)}</h3><p>${esc(d.owner||'소유자 없음')} · ${ago(d.updated_at)}</p><div class="doc-meta"><span>v${d.version}</span><span>${fmt(d.chunk_count)} chunks</span><span class="status-pill ${d.embedded?'':'pending'}">${d.embedded?'검색 가능':'처리 중'}</span></div></article>`).join('')}
function renderGraph(g){const users=g.nodes.filter(n=>n.kind==='user'),groups=g.nodes.filter(n=>n.kind==='group'),W=900,H=Math.max(450,Math.max(users.length,groups.length)*80+60),pos={};users.forEach((n,i)=>pos[n.id]={x:90,y:60+i*80});groups.forEach((n,i)=>pos[n.id]={x:560,y:60+i*80});const edges=g.edges.map(e=>`<line class="graph-edge" x1="${pos[e.source]?.x+190||0}" y1="${pos[e.source]?.y+25||0}" x2="${pos[e.target]?.x||0}" y2="${pos[e.target]?.y+25||0}"/>`).join('');const nodes=g.nodes.map(n=>{const p=pos[n.id];return `<g class="graph-node ${n.kind}" transform="translate(${p.x},${p.y})"><rect width="190" height="50"/><text x="14" y="22"><tspan font-weight="700">${esc(n.label)}</tspan><tspan x="14" dy="16" fill="#8390a6">${esc(n.detail||'그룹')}</tspan></text></g>`}).join('');$('membershipGraph').innerHTML=g.nodes.length?`<svg viewBox="0 0 ${W} ${H}">${edges}${nodes}</svg>`:'<span class="empty">사용자와 그룹 관계가 없습니다.</span>'}
function renderLogs(items){state.logs=items;filterLogs()}function filterLogs(){const level=$('logLevel').value,rows=(state.logs||[]).filter(x=>!level||x.level===level);$('logRows').innerHTML=rows.length?rows.map(x=>`<div class="log-row"><span>${new Date(x.timestamp).toLocaleTimeString('ko-KR')}</span><span class="log-level ${esc(x.level)}">${esc(x.level||'INFO')}</span><span>${esc(x.service||x.logger)}</span><span>${esc(x.message)}</span></div>`).join(''):'<div class="log-row"><span>Loki에서 수집된 로그가 없습니다.</span></div>'}$('logLevel').onchange=filterLogs;
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const body=new FormData();body.append('file',f);$('uploadState').classList.remove('hidden');$('uploadState').textContent='문서를 업로드하고 Pipeline에 등록하는 중입니다…';try{const d=await api('/v1/documents',{method:'POST',body});$('uploadState').textContent=`${d.filename} 업로드 완료 · Job ${d.job_id.slice(0,10)}`;await refresh()}catch(err){$('uploadState').textContent=err.message}};
$('searchButton').onclick=async()=>{const q=$('query').value.trim();if(!q)return;$('results').innerHTML='<p class="empty">문서의 의미와 관계를 분석하는 중입니다…</p>';try{const d=await api('/v1/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,mode:'hybrid',top_k:8})});$('results').innerHTML=(d.results||[]).map(x=>`<article class="result-card"><div class="panel-head"><h3>${esc(x.filename)}</h3><span class="badge">${Number(x.score||x.relevance||0).toFixed(3)}</span></div><p>${esc(x.snippet||x.content||'')}</p></article>`).join('')||'<p class="empty">관련성이 높은 문서를 찾지 못했습니다.</p>'}catch(err){$('results').innerHTML=`<p class="error">${esc(err.message)}</p>`}};
async function boot(){if(state.access){start();return}try{state.me=await api('/v1/me');$('identityName').textContent=state.me.display_name;$('identityRole').textContent=state.me.role.toUpperCase();$('identityAvatar').textContent=state.me.display_name.slice(0,1);$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await refresh();state.timer=setInterval(refresh,5000)}catch{}}
boot();
